
import AdmZip from "adm-zip";
import { libraryTemplateRepository } from "$lib/repositories/library-templates";
import type { LibraryTemplate, LibraryTemplateCreateInput } from "$lib/types/library-templates";
import { logger } from "$lib/logger";

interface ImportStats {
    success: number;
    failed: number;
    errors: Array<{ file: string; error: string }>;
}

export class LibraryExportImportService {
    /**
     * Export all library templates as a ZIP file containing JSON files
     */
    async exportLibrary(): Promise<Buffer> {
        try {
            const { items } = await libraryTemplateRepository.findAll({ limit: 10000 }); // Fetch all items
            const zip = new AdmZip();

            for (const item of items) {
                // Create a filename safe title
                const safeTitle = item.title.replace(/[^a-z0-9]/gi, "_").toLowerCase();
                const filename = `${item.id}_${safeTitle}.json`;
                const content = JSON.stringify(item, null, 2);
                zip.addFile(filename, Buffer.from(content, "utf8"));
            }

            return zip.toBuffer();
        } catch (error) {
            logger.error({ error }, "Failed to export library");
            throw error;
        }
    }

    /**
     * Import library templates from a ZIP file
     */
    async importLibrary(zipBuffer: Buffer): Promise<ImportStats> {
        const stats: ImportStats = {
            success: 0,
            failed: 0,
            errors: [],
        };

        try {
            const zip = new AdmZip(zipBuffer);
            const zipEntries = zip.getEntries();

            for (const entry of zipEntries) {
                if (!entry.entryName.endsWith(".json") || entry.isDirectory) {
                    continue;
                }

                try {
                    const content = entry.getData().toString("utf8");
                    const templateData = JSON.parse(content);

                    // Basic validation
                    if (!templateData.title || !templateData.type || !templateData.content) {
                        throw new Error("Invalid template format: missing required fields");
                    }

                    // Check if template exists
                    const existing = templateData.id
                        ? await libraryTemplateRepository.findById(templateData.id)
                        : null;

                    console.log("existing?", existing?.id, templateData.id)

                    if (existing) {
                        // Update existing
                        await libraryTemplateRepository.update(templateData.id, {
                            title: templateData.title,
                            description: templateData.description,
                            type: templateData.type,
                            category: templateData.category,
                            tags: templateData.tags,
                            content: templateData.content,
                            language: templateData.language,
                            preview: templateData.preview,
                            isActive: templateData.isActive,
                            version: templateData.version,
                            metadata: templateData.metadata
                        });
                    } else {
                        // Create new
                        // Ensure we don't pass the ID if it's meant to be generated, 
                        // but if we want to preserve IDs from export, we should probably check if we can.
                        // valid create input shouldn't have ID as it is generated by code usually, 
                        // but here we might want to preserve it if possible or better let it regenerate 
                        // to avoid primary key collisions if the ID strategy changes (though here it's likely UUID/ObjectId).
                        // The repository create method generates a new ID. 
                        // If we want to support restoring with same ID, we might need repository change or just let it create new.
                        // Let's create new to avoid collision issues for now, or maybe try to match by title?
                        // Existing logic: match by ID. If not found, create new.

                        const createInput: LibraryTemplateCreateInput = {
                            id: templateData.id,
                            title: templateData.title,
                            description: templateData.description,
                            type: templateData.type,
                            category: templateData.category,
                            tags: templateData.tags,
                            content: templateData.content,
                            language: templateData.language,
                            preview: templateData.preview,
                            version: templateData.version,
                            metadata: templateData.metadata
                        };

                        await libraryTemplateRepository.create(createInput);
                    }

                    stats.success++;
                } catch (error) {
                    stats.failed++;
                    stats.errors.push({
                        file: entry.entryName,
                        error: error instanceof Error ? error.message : String(error),
                    });
                }
            }
        } catch (error) {
            logger.error({ error }, "Failed to import library zip");
            throw error;
        }

        return stats;
    }
}

export const libraryExportImportService = new LibraryExportImportService();
